env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  react/prop-types: 0,
  no-underscore-dangle: 0,
  consistent-return: 0,
  react/function-component-definition: 0,
  import/prefer-default-export: 0,
  no-plusplus: 0,
  max-len: [1, { code: 120 }],
  no-console: 1
}
